### ISSUE TITLE
Please consider comments 

### ISSUE THREAD

**Issue by Geonhee-LEE** [Geonhee-LEE/rl-collision-avoidance#4]
It is different between comment and return. If you don't follow the regulation like below, I can't understand your intention.
```
    def forward(self, x, goal, speed):
        """
            returns value estimation, action, log_action_prob
        """
        return action, logprob, mean
```

**Comment by Geonhee-LEE** [comment]
@CzJaewan 재완아 봤으면 체크 후 변경(요청한 작업 완료)한 뒤 close and comment 혹은 Pull request 진행해주길 바람.

**Comment by CzJaewan** [comment]
branch td3 주석 수정 완료
